### ISSUE TITLE
[BUG] "Failed to install"

### ISSUE THREAD

**Issue by asmitde** [flybywiresim/installer#181]
**Installer Version**
1.1.1

**Describe the bug**

Fails to install the Development version. The installer starts downloading different modules, but at the end it says failed to install.
The Stable and Custom FBW versions install fine.

**To Reproduce**

1. Have any version of A32NX installed.
2. Switch to or update Development version. - Fails
3. Switch to Stable or Custom FBW version. - Works.

**Expected behavior**

All versions should be able to install properly.

**Additional context**

I had the development version installed prior to the installer update to 1.1.1. I updated the installer and then tried to update the Development version of A32NX.
![image](https://user-images.githubusercontent.com/23269916/112040057-181f1480-8b1b-11eb-8c1c-2be02b14e30b.png)

Discord username (if different from GitHub):
FltsimFlyboy#8725

**Comment by FoxtrotSierra6829** [comment]
Please check if there is any relation to #179 and if the mentioned workarounds work for you

**Comment by asmitde** [comment]
Yes, I just checked. My installer is not stuck as mentioned in #179, but it does fail with a notification.

I deleted the entire aircraft package from the community folder, and the installer was able to download the full module and install the latest dev version properly. However, updating or switching to the dev version from any other version still fails.

**Comment by FoxtrotSierra6829** [comment]
Please download [this version of the FlyByWire Installer](https://github.com/flybywiresim/installer/releases/download/vmaster/setup.exe) which contains additional logging capabilities. Open the dev tools by `CTRL+F12`, run the installation process, and after it failed, right click on any item in the console at the bottom right, and hit `save as` to save the log of this. Please send the log to us then. That would help us a lot to better identify the problem, thanks.

**Comment by Valastiri** [comment]
Mostly discussed on server, dumping logs here as well. 

![image](https://user-images.githubusercontent.com/1619968/112064808-8953db80-8b9e-11eb-8e66-7708e8535d71.png)

[setup logs.txt](https://github.com/flybywiresim/installer/files/6185553/setup.logs.txt)

**Comment by fullerhkz** [comment]
Same error installing dev version.
Attached the same file in two extensions
[setup logs.txt](https://github.com/flybywiresim/installer/files/6186367/setup.logs.txt)
[setup.log](https://github.com/flybywiresim/installer/files/6186369/setup.log)

**Comment by FoxtrotSierra6829** [comment]
Thanks for the help. **We have probably identified the issue, which turns out to be a CDN issue where every download pulled from the POP in New York provides old data which then doesn't match the checks.**

**Comment by fullerhkz** [comment]
Ok, Thanks.

Em seg., 22 de mar. de 2021 às 23:13, Florian Scheuner <
***@***.***> escreveu:

**Comment by nistei** [comment]
We've traced the issue back to our CDN provider and have resolved it. All downloads should be working now.

**Comment by asmitde** [comment]
Awesome! Thanks for the quick resolution. I just tried switching between different versions and it is installing fine now.

**Comment by Fawalken** [comment]
Getting "Failed to Install" when I clean install the dev version, meaning no previous version installed. If I install Stable, then switch to Dev, it works - seemingly because it is downloading modules rather than the full install. Getting this error in the logging installer, full log attached.
[-1616481119700.log](https://github.com/flybywiresim/installer/files/6187434/-1616481119700.log)

index.esm.js:5901 Downloading file full.zip
index.esm.js:5906 Downloading from https://cdn.flybywiresim.com/addons/a32nx/master/full.zip
index.esm.js:5907 GET https://cdn.flybywiresim.com/addons/a32nx/master/full.zip net::ERR_HTTP2_PROTOCOL_ERROR 200

**Comment by Valastiri** [comment]
[-1616482456023.log](https://github.com/flybywiresim/installer/files/6187480/-1616482456023.log)
Similar issue different error. 

```
index.js:350 Downloading file full.zip
cdn.flybywiresim.com/addons/a32nx/master/full.zip:1 Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
index.js:32 TypeError: network error
(anonymous) @ index.js:32
```

The rest of the log is swapping to Stable then swapping back to Development.

**Comment by jartweb** [comment]
[stable-to-dev.txt](https://github.com/flybywiresim/installer/files/6188005/stable-to-dev.txt)

Some problems remain. Seem to be related to encrypted locations.

1. Using existing v1.1.1 installer at ~08:15 UTC 2021-03-23 to perform Update to Dev version - gets stuck at 'Preparing update'.
2. Re-download v1.1.1 installer. Try again. Same issue.
2. Delete folder flybywire-aircraft-a320-neo from Community folder.
3. Try v1.1.1 installer to install Dev version. Downloads files, then gives 'Failed to install' error.
4. Ensure folder is still not present - check.
5. Try v1.1.1 installer to install Stable version - installs OK.
6. Try v1.1.1 installer to switch to Dev version - gets stuck at 'Preparing update'.
7. Try the debug version of the installer to switch from Stable to Dev - fails and generates attached log.
8. Investigate the two folders in question in the log:
 
D:\WpSystem\S-1-5-21-2461915082-4199115091-756499880-1001\AppData\Local\Packages\Microsoft.FlightSimulator_8wekyb3d8bbwe\LocalCache\Packages\Community\flybywire-aircraft-a320-neo\zh-CN.locPak ==== this folder exists and the file is located there

C:\Users\[redacted]\AppData\Local\Temp\flybywire_installer\zh-CN.locPak ==== this folder exists but the file is not copied there.

If I try to manually copy from the D to C locations I get a warning that the item being copied is encrypted but the destination folder does not support encryption. I _can_ manually copy the file there but if I then try to run the installer, the file is deleted and the error recurs.

For info, FS2020 is 'installed' to D by which I mean that I specified the D drive for the install and the majority of the files are in the location D:\WpSystem\S-1-5-21-2461915082-4199115091-756499880-1001 (it is 178 GB).

**Comment by jartweb** [comment]
Curious. 
Final test before heading off to work. 
After several attempts to unzip the Dev mode to the Community folder which resulted in only the default A320 being available in FS2020, I retried step 4 from above. This time, downloaded OK (log attached).
Not had chance to see if it flies, but the smooth install gives confidence.
Wonder if the previous attempts had something stuck in the cache.
[dev-install-clean.txt](https://github.com/flybywiresim/installer/files/6188542/dev-install-clean.txt)

**Comment by Fawalken** [comment]
> Getting "Failed to Install" when I clean install the dev version, meaning no previous version installed. If I install Stable, then switch to Dev, it works - seemingly because it is downloading modules rather than the full install. Getting this error in the logging installer, full log attached.
> [-1616481119700.log](https://github.com/flybywiresim/installer/files/6187434/-1616481119700.log)
> 
> index.esm.js:5901 Downloading file full.zip
> index.esm.js:5906 Downloading from https://cdn.flybywiresim.com/addons/a32nx/master/full.zip
> index.esm.js:5907 GET https://cdn.flybywiresim.com/addons/a32nx/master/full.zip net::ERR_HTTP2_PROTOCOL_ERROR 200

Just tried again today, install of dev went fine. All good here. Thank you for all the hard work.
